/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UcommReqApptForm {
    }
    interface UcommTextInput {
        "inputId": string;
        "placeholder": string;
        "stateTarget": string;
    }
}
declare global {
    interface HTMLUcommReqApptFormElement extends Components.UcommReqApptForm, HTMLStencilElement {
    }
    var HTMLUcommReqApptFormElement: {
        prototype: HTMLUcommReqApptFormElement;
        new (): HTMLUcommReqApptFormElement;
    };
    interface HTMLUcommTextInputElement extends Components.UcommTextInput, HTMLStencilElement {
    }
    var HTMLUcommTextInputElement: {
        prototype: HTMLUcommTextInputElement;
        new (): HTMLUcommTextInputElement;
    };
    interface HTMLElementTagNameMap {
        "ucomm-req-appt-form": HTMLUcommReqApptFormElement;
        "ucomm-text-input": HTMLUcommTextInputElement;
    }
}
declare namespace LocalJSX {
    interface UcommReqApptForm {
        "onTestEvent"?: (event: CustomEvent<Object>) => void;
    }
    interface UcommTextInput {
        "inputId": string;
        "onUcTextInput"?: (event: CustomEvent<Object>) => void;
        "placeholder"?: string;
        "stateTarget"?: string;
    }
    interface IntrinsicElements {
        "ucomm-req-appt-form": UcommReqApptForm;
        "ucomm-text-input": UcommTextInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ucomm-req-appt-form": LocalJSX.UcommReqApptForm & JSXBase.HTMLAttributes<HTMLUcommReqApptFormElement>;
            "ucomm-text-input": LocalJSX.UcommTextInput & JSXBase.HTMLAttributes<HTMLUcommTextInputElement>;
        }
    }
}
